#!/bin/bash

# Amzur Lead Engine - Quick Reference
# Copy these commands for quick access

echo "=========================================="
echo "🚀 AMZUR LEAD ENGINE - QUICK COMMANDS"
echo "=========================================="

echo ""
echo "📦 INITIAL SETUP"
echo "----------------------------------------"
echo "pnpm install                  # Install all dependencies"
echo "docker-compose up -d          # Start infrastructure services"
echo "cp .env.example .env          # Create environment file"
echo "pnpm db:generate              # Generate Prisma client"
echo "pnpm db:push                  # Setup database"

echo ""
echo "🔧 DEVELOPMENT"
echo "----------------------------------------"
echo "pnpm dev                      # Start all apps (frontend + API)"
echo "pnpm build                    # Build all apps"
echo "pnpm lint                     # Run linters"
echo "pnpm format                   # Format code"
echo "pnpm clean                    # Clean build artifacts"

echo ""
echo "💾 DATABASE"
echo "----------------------------------------"
echo "pnpm db:generate              # Generate Prisma client"
echo "pnpm db:push                  # Push schema changes"
echo "pnpm db:migrate               # Create migration"
echo "pnpm db:studio                # Open Prisma Studio"

echo ""
echo "🐳 DOCKER"
echo "----------------------------------------"
echo "docker-compose up -d          # Start services"
echo "docker-compose down           # Stop services"
echo "docker-compose down -v        # Stop and remove volumes"
echo "docker-compose logs -f        # View logs"
echo "docker-compose ps             # List services"
echo "docker-compose restart        # Restart all"

echo ""
echo "🤖 AI AGENTS"
echo "----------------------------------------"
echo "cd agents/discovery-agent && pnpm dev"
echo "cd agents/signal-agent && pnpm dev"
echo "cd agents/qualification-agent && pnpm dev"
echo "cd agents/enrichment-agent && pnpm dev"
echo "cd agents/outreach-agent && pnpm dev"

echo ""
echo "🌐 ACCESS POINTS"
echo "----------------------------------------"
echo "Frontend:     http://localhost:3000"
echo "Backend API:  http://localhost:3001"
echo "API Docs:     http://localhost:3001/api/docs"
echo "Prisma Studio: pnpm db:studio"

echo ""
echo "📊 DOCKER SERVICES"
echo "----------------------------------------"
echo "PostgreSQL:   localhost:5432"
echo "Redis:        localhost:6379"
echo "Elasticsearch: localhost:9200"

echo ""
echo "🔍 DEBUGGING"
echo "----------------------------------------"
echo "docker-compose logs postgres  # PostgreSQL logs"
echo "docker-compose logs redis     # Redis logs"
echo "docker exec -it amzur-postgres psql -U postgres -d amzur_lead_engine"
echo "docker exec -it amzur-redis redis-cli"

echo ""
echo "🧹 CLEANUP"
echo "----------------------------------------"
echo "pnpm clean                    # Clean node_modules and build files"
echo "docker-compose down -v        # Remove Docker volumes"
echo "rm -rf node_modules           # Remove all node_modules"
echo "rm -rf .next dist .turbo      # Remove build artifacts"

echo ""
echo "📚 DOCUMENTATION"
echo "----------------------------------------"
echo "README.md                     # Project overview"
echo "WORKSPACE_SUMMARY.md          # Complete setup summary"
echo "docs/SETUP.md                 # Detailed setup guide"
echo "docs/ARCHITECTURE.md          # System architecture"
echo "docs/API.md                   # API documentation"
echo "CONTRIBUTING.md               # Contribution guide"

echo ""
echo "=========================================="
echo "✅ Setup complete! Run 'pnpm dev' to start"
echo "=========================================="
