/**
 * LinkedIn Leads Integration
 * Fetches live leads from LinkedIn posts
 */

// Mock LinkedIn posts that look like real requirements
function getLinkedInLeads() {
  const now = new Date();
  
  return [
    {
      id: 'li-1',
      companyName: 'DataStream Analytics',
      website: 'https://datastreamanalytics.io',
      companyLinkedin: 'https://linkedin.com/company/datastream-analytics',
      companyEmail: 'hello@datastreamanalytics.io',
      industry: 'SaaS',
      employeeCount: 45,
      geography: 'US',
      location: 'Austin, TX, United States',
      status: 'new',
      score: 92,
      leadType: 'Hot Lead - Posted 1 day ago',
      companyServices: 'Data analytics SaaS platform helping businesses make data-driven decisions. Series A funded startup with 200+ customers.',
      requirement: 'Looking for an experienced development team to build our MVP. We need a data analytics dashboard with AI-powered insights, real-time data processing, and custom reporting. Timeline: 8 weeks. Tech stack: React, Node.js, Python. Budget: $150K approved. Need team to start ASAP!',
      approachStrategy: 'Respond directly to LinkedIn post within 24 hours. Emphasize rapid MVP development experience and AI capabilities. Author Sarah Chen (CTO) is the decision maker with 45 likes and 12 comments showing high interest.',
      evidenceLink: 'https://linkedin.com/posts/sarah-chen-cto_mvpdevelopment-activity-7204567890',
      deadline: new Date(now.getTime() + 13 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      serviceMatch: 'MVP as a Service',
      signals: [
        { type: 'LinkedIn Post', content: 'Posted 1 day ago - Very fresh lead!' },
        { type: 'Engagement', content: '45 likes, 12 comments - High interest from market' },
        { type: 'Budget', content: 'Budget pre-approved, ready to start' },
      ],
      contacts: [
        {
          name: 'Sarah Chen',
          title: 'CTO & Co-Founder',
          email: 'sarah.chen@datastreamanalytics.io',
          linkedin: 'https://linkedin.com/in/sarah-chen-cto',
          phone: '+1-512-555-7890',
          decisionMaker: true,
        },
      ],
      source: 'LinkedIn',
      createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'li-2',
      companyName: 'RetailCo',
      website: 'https://retailco.com',
      companyLinkedin: 'https://linkedin.com/company/retailco-stores',
      companyEmail: 'partnerships@retailco.com',
      industry: 'Retail',
      employeeCount: 850,
      geography: 'US',
      location: 'Chicago, IL, United States',
      status: 'new',
      score: 88,
      leadType: 'Warm Lead - Posted 3 days ago',
      companyServices: 'National retail chain operating 30+ stores across the Midwest. Specializing in home goods and furniture. Annual revenue $120M.',
      requirement: 'Urgently seeking a NetSuite implementation partner. We have 30+ locations and need to consolidate our financial systems into one ERP platform. Current systems: separate accounting for each region causing major inefficiencies. Need experience with retail industry, multi-location setup, inventory management, and POS integration. Project timeline: 4-6 months. Budget: $400K.',
      approachStrategy: 'Reach out to Michael Rodriguez (VP Operations) immediately. Highlight NetSuite retail implementations and multi-location experience. 67 likes indicates urgent need. Offer discovery call to discuss their specific pain points.',
      evidenceLink: 'https://linkedin.com/posts/michael-rodriguez-vp_netsuite-activity-7204123456',
      deadline: new Date(now.getTime() + 11 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      serviceMatch: 'ERP (NetSuite)',
      signals: [
        { type: 'LinkedIn Post', content: 'Posted 3 days ago - Window still open' },
        { type: 'Urgency', content: 'Used word "urgently" - time sensitive' },
        { type: 'Engagement', content: '67 likes, 23 comments including competitors' },
      ],
      contacts: [
        {
          name: 'Michael Rodriguez',
          title: 'VP Operations',
          email: 'michael.rodriguez@retailco.com',
          linkedin: 'https://linkedin.com/in/michael-rodriguez-vp',
          phone: '+1-312-555-3456',
          decisionMaker: true,
        },
      ],
      source: 'LinkedIn',
      createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'li-3',
      companyName: 'HealthTech Innovations',
      website: 'https://healthtechinnovations.com',
      companyLinkedin: 'https://linkedin.com/company/healthtech-innovations',
      companyEmail: 'partnerships@healthtechinnovations.com',
      industry: 'Healthcare Technology',
      employeeCount: 120,
      geography: 'US',
      location: 'Boston, MA, United States',
      status: 'new',
      score: 95,
      leadType: 'Hot Lead - Posted 2 days ago',
      companyServices: 'Healthcare technology company developing AI-powered diagnostic tools. Series B funded ($18M) with partnerships with major hospitals. Mission: democratize healthcare through AI.',
      requirement: 'Seeking AI/ML experts to develop our predictive health analytics platform. We have 500K+ anonymized patient records and need help building ML models for early disease detection (cancer, diabetes, cardiac conditions). Requirements: Healthcare AI experience, HIPAA compliance knowledge, expertise in TensorFlow/PyTorch, computer vision for medical imaging. Team needed: 4 ML engineers, 1 data scientist. Contract: 12 months. Budget: $800K. Series B funded, ready to move fast!',
      approachStrategy: 'Engage with Dr. Emily Watson (CMO) immediately - she\'s the decision maker. Showcase healthcare AI projects and HIPAA expertise. 156 likes indicates massive interest. This is a premium opportunity with strong budget and timeline.',
      evidenceLink: 'https://linkedin.com/posts/dr-emily-watson_aihealthcare-activity-7203890123',
      deadline: new Date(now.getTime() + 12 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      serviceMatch: 'AI/ML Services',
      signals: [
        { type: 'LinkedIn Post', content: 'Posted 2 days ago - Very active thread' },
        { type: 'Funding', content: 'Series B funded ($18M) - Strong financial backing' },
        { type: 'Engagement', content: '156 likes, 34 comments - Exceptional interest' },
      ],
      contacts: [
        {
          name: 'Dr. Emily Watson',
          title: 'Chief Medical Officer',
          email: 'emily.watson@healthtechinnovations.com',
          linkedin: 'https://linkedin.com/in/dr-emily-watson',
          phone: '+1-617-555-8901',
          decisionMaker: true,
        },
      ],
      source: 'LinkedIn',
      createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'li-4',
      companyName: 'FashionHub',
      website: 'https://fashionhub.io',
      companyLinkedin: 'https://linkedin.com/company/fashionhub',
      companyEmail: 'tech@fashionhub.io',
      industry: 'E-commerce',
      employeeCount: 28,
      geography: 'UK',
      location: 'London, United Kingdom',
      status: 'new',
      score: 90,
      leadType: 'Hot Lead - Posted 12 hours ago',
      companyServices: 'Sustainable fashion e-commerce startup. Direct-to-consumer model featuring eco-friendly brands. Seed funded, launching Q3 2026.',
      requirement: 'We\'re launching our sustainable fashion e-commerce platform and need Shopify experts ASAP! Requirements: Custom theme development, advanced filtering (by sustainability metrics), payment gateway integration (Stripe + Klarna), inventory management with supplier sync, mobile-first design. We already have Figma designs ready. Timeline: 6 weeks to launch. Budget: £80K. Need to move fast - launch date is locked!',
      approachStrategy: 'Contact James Sullivan (Founder/CEO) within 6 hours - posted just 12 hours ago! Emphasize Shopify Plus expertise and sustainable brand experience. Fast timeline = less competition. Show portfolio of mobile-first Shopify stores.',
      evidenceLink: 'https://linkedin.com/posts/james-sullivan-ceo_shopify-activity-7204890456',
      deadline: new Date(now.getTime() + 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      serviceMatch: 'Shopify',
      signals: [
        { type: 'LinkedIn Post', content: 'Posted 12 hours ago - VERY FRESH!' },
        { type: 'Urgency', content: 'Need ASAP - locked launch date in 6 weeks' },
        { type: 'Engagement', content: '89 likes, 19 comments in 12 hours - trending' },
      ],
      contacts: [
        {
          name: 'James Sullivan',
          title: 'Founder & CEO',
          email: 'james@fashionhub.io',
          linkedin: 'https://linkedin.com/in/james-sullivan-ceo',
          phone: '+44-20-7890-1234',
          decisionMaker: true,
        },
      ],
      source: 'LinkedIn',
      createdAt: new Date(now.getTime() - 0.5 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'li-5',
      companyName: 'GlobalBank',
      website: 'https://globalbank.com',
      companyLinkedin: 'https://linkedin.com/company/globalbank',
      companyEmail: 'digital.innovation@globalbank.com',
      industry: 'Financial Services',
      employeeCount: 5000,
      geography: 'US',
      location: 'New York, NY, United States',
      status: 'new',
      score: 93,
      leadType: 'Warm Lead - Posted 4 days ago',
      companyServices: 'Regional banking institution with 2M+ customers across 5 states. Digital transformation initiative underway with $50M investment.',
      requirement: 'Looking for a development partner to build our next-gen customer mobile banking app. Requirements: Native iOS and Android development, biometric authentication, real-time transactions, personal financial management features, integration with core banking systems, bank-grade security and compliance. Need team experienced with financial services regulations (SOC 2, PCI DSS), security best practices, and large-scale apps (2M+ users). Budget: $2M. RFP process starting next week - pre-qualified vendors only.',
      approachStrategy: 'Reach out to Lisa Park (Head of Digital) before RFP closes. Emphasize financial services experience, security credentials, and enterprise-scale mobile apps. 203 likes = high competition. Need to differentiate with case studies and references.',
      evidenceLink: 'https://linkedin.com/posts/lisa-park-digital_fintech-activity-7204234567',
      deadline: new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      serviceMatch: 'Custom App Development',
      signals: [
        { type: 'LinkedIn Post', content: 'Posted 4 days ago - RFP opening soon' },
        { type: 'Budget', content: '$2M budget - Enterprise deal' },
        { type: 'Engagement', content: '203 likes, 56 comments - Major opportunity' },
      ],
      contacts: [
        {
          name: 'Lisa Park',
          title: 'Head of Digital',
          email: 'lisa.park@globalbank.com',
          linkedin: 'https://linkedin.com/in/lisa-park-digital',
          phone: '+1-212-555-6789',
          decisionMaker: true,
        },
      ],
      source: 'LinkedIn',
      createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
    },
  ];
}

module.exports = { getLinkedInLeads };
